apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hazelcast.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    harness.io/skip-versioning: "true"
data:
  hazelcast.yaml: |-
{{ tpl (.Files.Get "config-files/hazelcast.yaml.tpl") . | indent 4 }}